Allow users to use classpath to set append jar dependencies (#1703)
Fixes #1681 

This change builds upon the changes introduced in #1395
This enables using user-defined classPath to be used as JAR cmd
dependencies for the core-tools module.
In addition, users can set ENV Variables that will be evaluated during
runTime.

### Usage
Assume that users have installed SPARK and they have `SPARK_HOME`
defined in their environment.
We can define a config dependency like the following -

```yaml
api_version: '1.2'
runtime:
  dependencies:
    - name: my-spark331
      uri: !ENV ${SPARK_HOME}/jars/*
      dependency_type:
        dep_type: classpath
```
Where uri: any valid sequence of java classPath separated by "`:`" ([See
valid
classPath](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/classpath.html#:~:text=classpath1%3Aclasspath2,character%20are%20ignored)).
Remember that JVM ignore any parts that do not exist.
Note: Only local path can be accepted. In order to dependency stored
remotely, please refer to the other types of dependencies described in
#1395

This also adds additional validation to the `RuntimeDependency` model:
- no usage of `relative_path` param with `File` dependency
- ensuring no `relative_path`, `archive` is provided with `classpath`
dependency

### Improvements in Download tasks

This PR also contains the changes for proper time out of dependency
downloads. The issue with that was the for streaming downloads, even in
case of the future timing out, the underlying request download keeps on
going in the background, which does not cancel the future run as well.
There are some additional tests as well that ensure that the downloads
work as expected

### Testing ->

* Local Machine run with a `tools_config` file as above and `SPARK_HOME`
not set-

The respective Java command that is submitted ( some params redacted )
->
  ```
2025-06-02 16:43:34,099 DEBUG rapids.tools.cmd: submitting system
command: <java -XX:+UseG1GC -Xms3g -Xmx6g -cp
/Directory/output-folder/qual_20250602164334_dfcAa9dC/work_dir/rapids-4-spark-tools_2.12-25.04.1.jar:N/A/jars/*
com.nvidia.spark.rapids.tool.qualification.QualificationMain
/Directory/event-logs/application_1.zstd
  ```
  
  This scenarios fails with the error ->
  ```
| Error: Unable to initialize main class
com.nvidia.spark.rapids.tool.qualification.QualificationMain
| Caused by: java.lang.NoClassDefFoundError:
org/apache/spark/internal/Logging
  ```
  
  Reason->
The `SPARK_HOME` gets replaced by `N/A` due to yaml replacement and in
that scenario the underlying command fails as it is not able to find the
required classes

* Local Machine run with the same `tools_config` file as above and
`SPARK_HOME` set ->

The respective Java command that is submitted ( some params redacted )
->
  ```
<CMD: java -XX:+UseG1GC -Xmx6g -cp
/Directory/output-folder/qual_20250602165118_9B07Ee4e/work_dir/rapids-4-spark-tools_2.12-25.04.1.jar:/opt/homebrew/Cellar/apache-spark/3.5.5/libexec/jars/*
com.nvidia.spark.rapids.tool.qualification.QualificationMain --platform
onprem /Directory/event-logs/application_1.zstd>
  ```
  
  Reason->
The run goes through successfully picking up the dependencies from the
specified classpath

* `Dataproc` run with default `SPARK_HOME` (`/usr/lib/spark`) and tools
config same as above ->

  The respective java command that is submitted ->
  ```
<CMD: java -XX:+UseG1GC -Xms6g -Xmx13g -cp
/home/work_dir/rapids-4-spark-tools_2.12-25.04.2-SNAPSHOT.jar:/usr/lib/hadoop/etc/hadoop:/usr/lib/spark/jars/*
com.nvidia.spark.rapids.tool.qualification.QualificationMain --platform
dataproc /home/sbari_nvidia_com/application_1.zstd>
  ```

  Works as expected, without downloading the spark dependencies.

---------

Signed-off-by: Sayed Bilal Bari <sbari@nvidia.com>
Signed-off-by: sayedbilalbari <145510907+sayedbilalbari@users.noreply.github.com>