Revert "Follow Up: Make '--platform' argument mandatory in CLI (#1473)" (#1498)
Fixes #1497. 

In https://github.com/NVIDIA/spark-rapids-tools/issues/1472, the
`--platform` argument was made a required parameter in Fire. In our
tests, it was found that the short flag -p for platform is no longer
functioning.

Upon investigation, it seems that Fire does not support short flags for
required arguments.

This PR reverts the above commit and makes the platform argument
optional in Fire. This change will ensure compatibility with the -p
flag.

The platform argument will still be validated internally to ensure its
requirement is enforced.


### Case 1 : Platform not provided

```
spark_rapids qualification  --eventlogs "/path/to/dataproc-cpu" --verbose
```

#### STDOUT

```

2025-01-10 13:35:16,011 INFO spark_rapids_tools.argparser: ...applying argument case: Missing Platform argument
2025-01-10 13:35:16,012 ERROR spark_rapids_tools.argparser: Validation err: 1 validation error for QualifyUserArgModel
  Cannot run tool cmd without platform argument. Re-run the command providing the platform argument.
  Error: [type=invalid_argument, input_value=ArgsKwargs((), {'eventlog...ols_config_path': None}), input_type=ArgsKwargs]
```



### Case 2: Platform provided by `--platform` and `-p`

```
spark_rapids qualification --platform dataproc --eventlogs "/path/to/dataproc-cpu" --verbose
spark_rapids qualification -p dataproc --eventlogs "/path/to/dataproc-cpu" --verbose
```


#### STDOUT
```
Report Summary:
----------------------  -
Total applications      1
Processed applications  1
Top candidates          0
----------------------  -


Processing Completed!
```

---------

Signed-off-by: Partho Sarthi <psarthi@nvidia.com>